Математический метод

In [1]:
import numpy as np
s=np.array([27,37,42,48,57,56,77,80])
p=np.array([1.2,1.6,1.8,1.8,2.5,2.6,3,3.3])

In [3]:
n=len(s)
n

8

In [4]:
b1=(n*np.sum(s*p)-np.sum(s)*np.sum(p))/(n*np.sum(s**2)-np.sum(s)**2)
b1

0.03874584717607981

In [6]:
b1=(np.mean(s*p)-np.mean(s)*np.mean(p))/(np.mean(s**2)-np.mean(s)**2)
b1

0.03874584717607981

In [7]:
b0 = np.mean(p) - b1*np.mean(s)
b0

0.17147009966776983

y_pred = 0.17147 + 0.038746*s

In [8]:
y_pred = b0 + b1*s

In [9]:
y_pred 

array([1.21760797, 1.60506645, 1.79879568, 2.03127076, 2.37998339,
       2.34123754, 3.15490033, 3.27113787])

In [10]:
mse = ((p - y_pred)**2).sum() /n
mse

0.020001557308970096

Матричный метод

In [15]:
x = s.reshape((8,1))
x

array([[27],
       [37],
       [42],
       [48],
       [57],
       [56],
       [77],
       [80]])

In [16]:
y = p.reshape((8,1))
y

array([[1.2],
       [1.6],
       [1.8],
       [1.8],
       [2.5],
       [2.6],
       [3. ],
       [3.3]])

Добавляем столбец единиц в матрицу Х. Единицы это b0 (a)

In [17]:
X=np.hstack([np.ones((8,1)),x])
X

array([[ 1., 27.],
       [ 1., 37.],
       [ 1., 42.],
       [ 1., 48.],
       [ 1., 57.],
       [ 1., 56.],
       [ 1., 77.],
       [ 1., 80.]])

In [18]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)), X.T @ y)
B

array([[0.1714701 ],
       [0.03874585]])

Градиентный спуск

In [30]:
x=np.array([27,37,42,48,57,56,77,80])
y=np.array([1.2,1.6,1.8,1.8,2.5,2.6,3,3.3])

In [36]:
def mse_(B1, y=y, x=x, n=8):
  return np.sum((B1*x-y)**2)/n

In [37]:
alpha = 1e-6 # скорость обучения, в данном случае одна миллионная

mse = 1/n * np.sum((B1*x-y)**2)

mse = 2/n * np.sum((B1 *x -y)*x)

In [38]:
B1=0.1 # минимальное стартовое значение
n=8

In [28]:
for i in range (10):
  B1 -=alpha*2/n *np.sum((B1 *x -y)*x)
  print('B1={}'.format(B1))

B1=0.09963717500000001
B1=0.0992766067715
B1=0.09891828127738128
B1=0.09856218456783597
B1=0.09820830277982404
B1=0.09785662213653352
B1=0.09750712894684428
B1=0.09715980960479491
B1=0.09681465058905309
B1=0.09647163846238918


In [39]:
for i in range (3000):
  B1 -=alpha*2/n *np.sum((B1 *x -y)*x)
  if i%500 ==0:
    print('Iteration = {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration = 0, B1=0.09963717500000001, mse=10.473767425934748
Iteration = 500, B1=0.044228497074524545, mse=0.04323672600561466
Iteration = 1000, B1=0.041781102969909154, mse=0.022886996112286277
Iteration = 1500, B1=0.041673001890302756, mse=0.022847294248723928
Iteration = 2000, B1=0.041668227079662334, mse=0.022847216791284503
Iteration = 2500, B1=0.04166801617689674, mse=0.022847216640166798


In [40]:
mse_(0.041668)

0.022847216640000008

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
model = LinearRegression()

In [44]:
s=s.reshape(-1,1)
s

array([[27],
       [37],
       [42],
       [48],
       [57],
       [56],
       [77],
       [80]])

In [45]:
regres=model.fit(s,p)

In [46]:
print(regres.intercept_)

0.1714700996677747


In [47]:
print(regres.coef_)

[0.03874585]


In [48]:
y_pred = model.predict(s)
y_pred

array([1.21760797, 1.60506645, 1.79879568, 2.03127076, 2.37998339,
       2.34123754, 3.15490033, 3.27113787])

In [53]:
s=np.array([27,37,42,48,57,56,77,80])
p=np.array([1.2,1.6,1.8,1.8,2.5,2.6,3,3.3])

In [54]:
r = np.corrcoef(s,p)[1,0]
r

0.9785768205829909

In [55]:
r**2

0.9576125937823151

In [59]:
from scipy import stats
stats.f.ppf(1-0.05, 1, 6)

5.987377607273699

In [62]:
SSf = sum((y_pred-np.mean(p))**2)
SSf

3.614987541528235

In [63]:
SSo = np.sum((p-y_pred)**2)
SSo

0.16001245847176088

In [65]:
MSf = SSf/(2-1)
MSf

3.614987541528235

In [66]:
MSo = SSo/(8-2)
MSo

0.02666874307862681

In [67]:
F=MSf/MSo
F

135.55147803067638

Так как 135 больше чем 5,99 (расчитано выше по формуле), значит принимаем альтернативную гипотезу